name: Update playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -U yt-dlp

      - run: python update_playlist.py

      - name: Commit playlist
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add playlist.m3u
          git commit -m "update playlist" || exit 0
          git pull --rebase origin main
          git push
